name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: wordcount-app/package-lock.json
    
    - name: Install Dependencies
      working-directory: ./wordcount-app
      run: npm ci
    
    - name: Lint Code
      working-directory: ./wordcount-app
      run: npm run lint
    
    - name: Build Project
      working-directory: ./wordcount-app
      run: npm run build
    
    - name: Run Tests
      working-directory: ./wordcount-app
      run: npm test
